POST http://127.0.0.1:8000/api/dummy HTTP/1.1
content-type:application/json

{
    "name":""
}

###
DELETE http://127.0.0.1:8000/api/dummy/1
content-type:application/json

###
PATCH http://127.0.0.1:8000/api/dummy/2 HTTP/1.1
content-type:application/json

{
    "name":"the modify one"
}

###
GET http://127.0.0.1:8000/api/dummy/2 
content-type:application/json

###
GET http://127.0.0.1:8000/api/dummy
content-type:application/json

###
GET http://127.0.0.1:8000/api/dummy?sorts=name:asc,id:desc&filters=name:nn
content-type:application/json